tmp_dir:
  "/scratch/fanslerm"

annotationFile:
  "data/cell-ann.csv"

sampleBatchFile:
  "data/sample_batch.txt"

metadataFile:
  "data/SRP126776.run_table.tsv"

gencodeGFF:
  "/data/mayrc/db/mm10/gencode.vM17.annotation.gff3.gz"

gencodeBED:
  "/data/mayrc/db/mm10/gencode.vM17.annotation.bed"

polyASiteBED:
  "/data/mayrc/db/mm10/polyASite.clusters.mm10.bed.gz"
  
ascpKeyFile:
  "~/.aspera/connect/etc/asperaweb_id_dsa.openssh"

adaptersFile:
  "microwell_seq_adapters.txt"

immuneSRRs:
  - SRR6954580
  - SRR6954579
  - SRR6954575
  - SRR6954568
  - SRR6954567
  - SRR6954566
  - SRR6954565
  - SRR6954564
  - SRR6954563
  - SRR6954509
  - SRR6954508
  - SRR6954507
  - SRR6954506
  - SRR6954505
  - SRR6954504
  - SRR6954503

barcodeRegex:
  '(?P<cell_1>.{6})(?P<discard_1>CGACTCACTACAGGG){s<=1}(?P<cell_2>.{6})(?P<discard_2>TCGGTGACACGATCG){s<=1}(?P<cell_3>.{6})(?P<umi_1>.{6})(?P<discard_3>T{12}){s<=2}.*'

minReadLength: 21

hisatIndex: "/data/mayrc/db/mm10/hisat2_mm10_genome"
